// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _05_EntityFramework;

#nullable disable

namespace _06_DataAccessAirport.Migrations
{
    [DbContext(typeof(AirportDbContext))]
    partial class AirportDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_05_EntityFramework.Models.Airplane", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MaxCountPassangers")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Airplanes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaxCountPassangers = 0,
                            Model = "AN747"
                        },
                        new
                        {
                            Id = 2,
                            MaxCountPassangers = 0,
                            Model = "AN746"
                        },
                        new
                        {
                            Id = 3,
                            MaxCountPassangers = 0,
                            Model = "AN746"
                        },
                        new
                        {
                            Id = 4,
                            MaxCountPassangers = 0,
                            Model = "AN744"
                        },
                        new
                        {
                            Id = 5,
                            MaxCountPassangers = 0,
                            Model = "AN743"
                        });
                });

            modelBuilder.Entity("_05_EntityFramework.Models.Client", b =>
                {
                    b.Property<int>("CredentialId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("FirstName");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("CredentialId");

                    b.ToTable("Passangers", (string)null);

                    b.HasData(
                        new
                        {
                            CredentialId = 1,
                            Birthdate = new DateTime(1995, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "vova@gmail.com",
                            Name = "Vova",
                            Rating = 0
                        },
                        new
                        {
                            CredentialId = 2,
                            Birthdate = new DateTime(2000, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ira@gmail.com",
                            Name = "Ira",
                            Rating = 0
                        },
                        new
                        {
                            CredentialId = 3,
                            Birthdate = new DateTime(2001, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nikita@gmail.com",
                            Name = "Nikita",
                            Rating = 0
                        },
                        new
                        {
                            CredentialId = 4,
                            Birthdate = new DateTime(2003, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sasha@gmail.com",
                            Name = "Sasha",
                            Rating = 0
                        },
                        new
                        {
                            CredentialId = 5,
                            Birthdate = new DateTime(2005, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "dima@gmail.com",
                            Name = "Dima",
                            Rating = 0
                        });
                });

            modelBuilder.Entity("_05_EntityFramework.Models.Credential", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Credentials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Login = "user1",
                            Password = "12345"
                        },
                        new
                        {
                            Id = 2,
                            Login = "user2",
                            Password = "12345"
                        },
                        new
                        {
                            Id = 3,
                            Login = "user3",
                            Password = "12345"
                        },
                        new
                        {
                            Id = 4,
                            Login = "user4",
                            Password = "12345"
                        },
                        new
                        {
                            Id = 5,
                            Login = "user5",
                            Password = "12345"
                        });
                });

            modelBuilder.Entity("_05_EntityFramework.Models.Flight", b =>
                {
                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Number"));

                    b.Property<int>("AirplaneId")
                        .HasColumnType("int");

                    b.Property<string>("ArrivalCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartureCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Number");

                    b.HasIndex("AirplaneId");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            Number = 1,
                            AirplaneId = 1,
                            ArrivalCity = "Kyiv",
                            ArrivalTime = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureCity = "Lviv",
                            DepartureTime = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Number = 2,
                            AirplaneId = 1,
                            ArrivalCity = "Kyiv",
                            ArrivalTime = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureCity = "Praga",
                            DepartureTime = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Number = 3,
                            AirplaneId = 1,
                            ArrivalCity = "Kyiv",
                            ArrivalTime = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureCity = "Warshaw",
                            DepartureTime = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Number = 4,
                            AirplaneId = 1,
                            ArrivalCity = "Kyiv",
                            ArrivalTime = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureCity = "Kharkiv",
                            DepartureTime = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("_06_DataAccessAirport.Models.ClientFlight", b =>
                {
                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.HasKey("ClientId", "FlightId");

                    b.HasIndex("FlightId");

                    b.ToTable("ClientFlights");

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            FlightId = 1
                        },
                        new
                        {
                            ClientId = 2,
                            FlightId = 1
                        },
                        new
                        {
                            ClientId = 3,
                            FlightId = 1
                        },
                        new
                        {
                            ClientId = 4,
                            FlightId = 2
                        },
                        new
                        {
                            ClientId = 5,
                            FlightId = 2
                        });
                });

            modelBuilder.Entity("_05_EntityFramework.Models.Client", b =>
                {
                    b.HasOne("_05_EntityFramework.Models.Credential", "Credential")
                        .WithOne("Client")
                        .HasForeignKey("_05_EntityFramework.Models.Client", "CredentialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Credential");
                });

            modelBuilder.Entity("_05_EntityFramework.Models.Flight", b =>
                {
                    b.HasOne("_05_EntityFramework.Models.Airplane", "Airplane")
                        .WithMany("Flights")
                        .HasForeignKey("AirplaneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airplane");
                });

            modelBuilder.Entity("_06_DataAccessAirport.Models.ClientFlight", b =>
                {
                    b.HasOne("_05_EntityFramework.Models.Client", "Client")
                        .WithMany("ClientFlights")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_05_EntityFramework.Models.Flight", "Flight")
                        .WithMany("ClientFlights")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("_05_EntityFramework.Models.Airplane", b =>
                {
                    b.Navigation("Flights");
                });

            modelBuilder.Entity("_05_EntityFramework.Models.Client", b =>
                {
                    b.Navigation("ClientFlights");
                });

            modelBuilder.Entity("_05_EntityFramework.Models.Credential", b =>
                {
                    b.Navigation("Client")
                        .IsRequired();
                });

            modelBuilder.Entity("_05_EntityFramework.Models.Flight", b =>
                {
                    b.Navigation("ClientFlights");
                });
#pragma warning restore 612, 618
        }
    }
}
